import uuid

from app.models.form import Form

GUEST_REGISTRATION_SCHEMA = {
    "required": [
        "first_name",
        "last_name",
        "residence_address",
        "birth_date",
        "phone",
        "email",
        "emergency_contact_name",
        "emergency_contact_phone",
        "vehicle_brand",
        "vehicle_model",
        "vehicle_registration_number",
    ],
    "properties": {
        "first_name": {"type": "string", "title": "Imię"},
        "last_name": {"type": "string", "title": "Nazwisko"},
        "pesel": {"type": "string", "title": "PESEL", "pattern": "^[0-9]{11}$"},
        "id_card_series": {"type": "string", "title": "Seria dowodu osobistego"},
        "id_card_number": {"type": "string", "title": "Numer dowodu osobistego"},
        "residence_address": {"type": "string", "title": "Adres zamieszkania"},
        "birth_date": {"type": "string", "format": "date", "title": "Data urodzenia"},
        "phone": {"type": "string", "title": "Telefon"},
        "email": {"type": "string", "format": "email", "title": "E-mail"},
        "emergency_contact_name": {
            "type": "string",
            "title": "Kontakt ICE – imię i nazwisko",
        },
        "emergency_contact_phone": {
            "type": "string",
            "title": "Kontakt ICE – telefon",
        },
        "vehicle_brand": {"type": "string", "title": "Marka pojazdu"},
        "vehicle_model": {"type": "string", "title": "Model pojazdu"},
        "vehicle_registration_number": {
            "type": "string",
            "title": "Numer rejestracyjny",
        },
    },
    "identity_document_rule": "pesel_or_id_card",
}

SAMPLE_GUEST_SUBMISSIONS: list[dict] = [
    {
        "participant_role": "driver",
        "vehicle_type": "car",
        "payload_json": {
            "first_name": "Jan",
            "last_name": "Kowalski",
            "pesel": "90010112345",
            "residence_address": "ul. Torowa 1, 00-001 Warszawa",
            "birth_date": "1990-01-01",
            "phone": "500600701",
            "email": "jan.kowalski@example.com",
            "emergency_contact_name": "Anna Kowalska",
            "emergency_contact_phone": "511222301",
            "vehicle_brand": "BMW",
            "vehicle_model": "M3",
            "vehicle_registration_number": "WX 12345",
        },
        "consents_json": {"terms": True, "privacy": True},
        "declarations_accepted": True,
    },
    {
        "participant_role": "passenger",
        "vehicle_type": "motorcycle",
        "payload_json": {
            "first_name": "Anna",
            "last_name": "Nowak",
            "id_card_series": "ABC",
            "id_card_number": "123456",
            "residence_address": "ul. Wyścigowa 5, 30-001 Kraków",
            "birth_date": "1995-05-20",
            "phone": "600700802",
            "email": "anna.nowak@example.com",
            "emergency_contact_name": "Piotr Nowak",
            "emergency_contact_phone": "601602603",
            "vehicle_brand": "Yamaha",
            "vehicle_model": "R6",
            "vehicle_registration_number": "KR 98765",
        },
        "consents_json": {"terms": True, "privacy": True},
        "declarations_accepted": True,
    },
    {
        "participant_role": "driver",
        "vehicle_type": "gokart",
        "payload_json": {
            "first_name": "Piotr",
            "last_name": "Wiśniewski",
            "pesel": "88021298765",
            "residence_address": "ul. Parkowa 12, 80-001 Gdańsk",
            "birth_date": "1988-02-12",
            "phone": "510510510",
            "email": "piotr.wisniewski@example.com",
            "emergency_contact_name": "Ewa Wiśniewska",
            "emergency_contact_phone": "512512512",
            "vehicle_brand": "Tony Kart",
            "vehicle_model": "Racer 401",
            "vehicle_registration_number": "GD 44556",
        },
        "consents_json": {"terms": True, "privacy": True},
        "declarations_accepted": True,
    },
    {
        "participant_role": "legal_guardian",
        "vehicle_type": "car",
        "payload_json": {
            "first_name": "Maria",
            "last_name": "Zielińska",
            "pesel": "75030345678",
            "residence_address": "ul. Słoneczna 8, 50-001 Wrocław",
            "birth_date": "1975-03-03",
            "phone": "503503503",
            "email": "maria.zielinska@example.com",
            "emergency_contact_name": "Tomasz Zieliński",
            "emergency_contact_phone": "504504504",
            "vehicle_brand": "Audi",
            "vehicle_model": "RS3",
            "vehicle_registration_number": "WR 11223",
        },
        "consents_json": {"terms": True, "privacy": True},
        "declarations_accepted": True,
    },
    {
        "participant_role": "driver",
        "vehicle_type": "motorcycle",
        "payload_json": {
            "first_name": "Tomasz",
            "last_name": "Lewandowski",
            "id_card_series": "XYZ",
            "id_card_number": "654321",
            "residence_address": "ul. Moto 3, 40-001 Katowice",
            "birth_date": "1992-11-11",
            "phone": "505505505",
            "email": "tomasz.lewandowski@example.com",
            "emergency_contact_name": "Katarzyna Lewandowska",
            "emergency_contact_phone": "506506506",
            "vehicle_brand": "Kawasaki",
            "vehicle_model": "Ninja 650",
            "vehicle_registration_number": "KT 77889",
        },
        "consents_json": {"terms": True, "privacy": True},
        "declarations_accepted": True,
    },
]


def guest_registration_form() -> Form:
    return Form(
        id=uuid.uuid4(),
        code="guest-registration",
        name="Rejestracja gościa",
        version="1.0",
        schema_json=GUEST_REGISTRATION_SCHEMA,
        pdf_template_path="templates/forms/guest-registration-v1.pdf",
        is_active=True,
    )
