"""Generic single-database configuration."""

from alembic import op
import sqlalchemy as sa



revision = '741d4280a258'
down_revision = 'f0f4afe3dfd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
